config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :beers
  resources :users
  resources :comments

  root 'welcome#index'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

end

app/models/beer.rb
class Beer < ActiveRecord::Base
  belongs_to :user
  has_many :comments

  validates :name, presence: true, uniqueness: true
  validates :category, :alc_percent, presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :beer

  validates :content, presence: true
  validates_length_of :content, :maximum => 500
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :beers
  has_many :comments

  validates :username, :password, :first_name, :last_name, :location, presence: true
  validates :username,  uniqueness: true
  validates_length_of :username,
  :in => 5..15
  validates_length_of :password,
  :in => 6..20
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
    helper_method :current_user

    def authorize
      redirect_to '/login' unless current_user
    end
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController

  before_filter :authorize

  def index
    @beers = Beer.all
  end

  def show
    @beer = Beer.find_by(id: params[:id])
    @comments = @beer.comments
  end

  def new
    @beer = Beer.new
  end

  def create
    beer = Beer.new(beer_params)
    if beer.save
      redirect_to "/beers/#{beer.id}"
    else
      redirect_to '/beers'
    end
  end

  def edit
    @beer = Beer.find_by(id: params[:id])
  end

  def update
    @beer = Beer.find_by(id: params[:id])
    if @beer.update_attributes(beer_params)
      redirect_to "/beers/#{@beer.id}"
    else
      redirect_to '/beers'
    end
  end

  private

  def beer_params
    params.require(:beer).permit(:name, :category, :alc_percent, :description).merge(:user_id => @current_user.id)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_filter :authorize

  def new
    @comment = Comment.new
  end

  def create
    @beer = Beer.find_by(id: params[:beer_id])
    comment = Comment.new(comment_params)
    if comment.save
      redirect_to "/comments/#{comment.id}"
    else
      redirect_to "/beers/#{beer.id}"
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content).merge(:user_id => @current_user.id, :beer_id => params[@beer.id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(:username[params[:username]])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to '/'
    else
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to '/'
    else
      redirect_to '/signup'
    end
  end

  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update_attributes(first_name: params[:first_name], last_name: params[:last_name], location: params[:location])
      redirect_to "/users/#{@user.id}"
    else
      redirect_to "/users/#{@user.id}"
    end
  end

  private
    def user_params
      params.require(:user).permit(:first_name, :last_name, :location, :username, :password, :password_confirmation)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/beers/edit.html.erb
<%= form_for(@beer, html: {method: "put"}) do |f| %>
  Name: <%= f.text_field :name %>
  Category: <%= f.text_field :category %>
  Percent Alcohol: <%= f.number_field :alc_percent, :class => 'text_field', :step => 'any' %>
  Description: <%= f.text_field :description %>
  <%= f.submit "Submit" %>
<% end %>

app/views/beers/index.html.erb
<h2>Beers</h2>

<a href="/beers/new">Add New Beer</a>

<div>
<% @beers.each do |b| %>
<ul>
  <li><a href="/beers/<%=b.id%>"><%=b.category%>: <%= b.name %> (<%=b.alc_percent%>)</a></li>
</ul>
<% end %>
</div>

app/views/beers/new.html.erb
<%= form_for @beer, url: {action: "create"} do |f| %>
  Name: <%= f.text_field :name %>
  Category: <%= f.text_field :category %>
  Percent Alcohol: <%= f.number_field :alc_percent, :class => 'text_field', :step => 'any' %>
  Description: <%= f.text_field :description %>
  <%= f.submit "Submit" %>
<% end %>

app/views/beers/show.html.erb
<h2><%=@beer.name%></h2>

<h4>Facts</h4>
  <ul>
    <li>Category: <%=@beer.category%></li>
    <li>Percent Alcohol: <%=@beer.alc_percent%></li>
    <li>Description: <%=@beer.description%></li>
  </ul>

<%= link_to "Add New Comment", new_comment_path %>
<h4>Comments</h4>
  <ul>
  <% @comments.each do |c| %>
    <li><%=c.content%></li>
  <%end%>
  </ul>

<% if current_user.id == @beer.user_id %>
<a href="/beers/<%=@beer.id%>/edit">Edit Beer</a>
<% end %>
<a href="/beers">Back to All Beers</a>

app/views/comments/new.html.erb
<%= form_for @comment, url: {action: "create"} do |f| %>

  Content: <%= f.text_field :content %>
  <%= f.submit "Submit" %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BeerGarden20</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if current_user %>
  Signed in as <a href="/users/<%=current_user.id%>"><%= current_user.username %></a> | <%= link_to "Beers", beers_path%> | <%= link_to "Logout", '/logout' %>
<% else %>
  <%= link_to 'Login', '/login' %> | <%= link_to 'Signup', '/signup' %>
<% end %>

<%= yield %>

</body>
</html>

app/views/users/edit.html.erb
<!-- TODO: FIX FORM -->

<%= form_for @user, url: {action: "update"} do |f| %>
  First Name: <%= f.text_field :first_name %>
  Last Name: <%= f.text_field :last_name %>
  Location: <%= f.text_field :location %>
  <%= f.submit "Submit" %>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for :user, url: '/users' do |f| %>

  Username: <%= f.text_field :username %>
  Password: <%= f.password_field :password %>
  Password Confirmation: <%= f.password_field :password_confirmation %>
  First Name: <%= f.text_field :first_name %>
  Last Name: <%= f.text_field :last_name %>
  Location: <%= f.text_field :location %>

  <%= f.submit "Submit" %>

<% end %>

app/views/users/show.html.erb
<h1><%=@user.username%></h1>
<h4>Last signed in at: <%=@user.updated_at%></h4>

<ul>
  <li>Name: <%=@user.first_name%> <%=@user.last_name%></li>
  <li>Location: <%=@user.location%></li>
</ul>

<a href="/users/<%=@user.id%>/edit">Edit My Information</a>
<a href="/beers/new">Add New Beer</a>

app/views/welcome/index.html.erb
<p>WELCOME TO BEERGARDEN</p>
<a href="/beers">See All Beers</a>